#!/usr/bin/env python3
from orange import Path
from orange.xlsx import Header
import sys

sys.path.insert(0, "src")

with Path("~/table3.xlsx").write_xlsx(force=True)as book:
    book.add_table(
        pos="A1",
        columns=[
            Header('姓名', width=12, format="normal"),
            Header('年龄', width=15, format='percent'),
        ],
        data=[
            ['张三', .23],
            ["历史", .34]
        ]

    )
    print('导出文件成功')
